[package]
name = "destiny-unpacker-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

libm = "0.2.2" #floor
libloading = "0.7" #oodle
openssl = "0.10.40" #AES-128-GCM decryption
chrono = "0.4.19" #time

[profile.dev]
opt-level = 1