[package]
name = "DestinyUnpackerRS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.40"
libm = "0.2.2"

# aes = "0.8.1"
# common_math = "0.3.0"
# half = "1.8.2"
# winapi = { version = "0.3.9", features = ["libloaderapi"] }
